// ==UserScript==
// @name        Base Share
// @description Base Share
// @namespace   https://cncapp*.alliances.commandandconquer.com/*/index.aspx*
// @include     https://cncapp*.alliances.commandandconquer.com/*/index.aspx*
// @icon        https://project-exception.net/download/scanner.png
// @downloadURL https://raw.githubusercontent.com/leo7044/CnC_TA/master/BaseShare.user.js
// @version     2021.01.16
// @author      TheStriker
// @contributor leo7044 (https://github.com/leo7044)
// ==/UserScript==
'use strict';(function(){var r=document.createElement("script");r.innerHTML="("+function(){function z(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++)if(-1!=a[b].innerHTML.search(/icon_efficiency_target_range/g)){document.getElementsByTagName("head")[0].removeChild(a[b]);break}}function A(){qx.Class.define("BaseShare",{type:"singleton",extend:qx.core.Object,members:{Trans:null,data:null,newData:null,processingData:null,cityData:{},updateTimeout:null,GetData:null,button:null,
requested:null,worldId:null,worldName:null,allianceId:null,playerId:null,playerName:null,Initialize:function(){try{this.GetData=this.FindMethod(ClientLib.Data.Cities.prototype,/OCITY/);"undefined"===typeof ClientLib.Data.WorldSector.WorldObjectNPCBase.prototype.get_Id&&this.QuickWrapProperty(ClientLib.Data.WorldSector.WorldObjectNPCBase.prototype,"$ctor",/this\.([A-Z]{6,12})\s*=\s*\(\w\.\$\w\s*=\s*\$I\.[A-Z]{6,12}\.[A-Z]{6,12}\(\w,\s*\w,\s*\w\),\s*\w\s*=\s*\w.\w,\s*\w\.\$\w\);\s*return\sthis;/,"get_Id");
if("undefined"===typeof ClientLib.Data.City.prototype.Update){var a=this.FindMethod(ClientLib.Data.City.prototype,/Math\.(?:floor|round)\(a\.adb\)/);this.AliasMethod(ClientLib.Data.City.prototype,a,"Update")}this.data=[];this.newData=[];this.processingData=[];this.requested=[];this.button=(new qx.ui.form.Button(null,"webfrontend/ui/icons/efficiency_icons/icon_efficiency_target_range.png")).set({padding:0,toolTipText:"BaseShare"});this.addButtonToDesktop(this.button);this.button.addListener("execute",
function(){setTimeout(this.Scan.bind(this),0)},this);this.resizeIcon(this.button.getChildControl("icon"),40);this.createAttackButtonPatch();this.createCityMovePatch();z()}catch(b){console.log("BaseShare.init: "+b.message,b),console.error(b,b.stack)}},AliasMethod:function(a,b,c){a[c]=a[b]},QuickWrapProperty:function(a,b,c,d){b=this.FindRegexSubStr(a[b],c,1);a[d]=(new Function("return function () {return this."+b+";}"))()},FindRegexSubStr:function(a,b,c){a="function"===typeof a?a.toString():a;a=b.exec(a);
if(null===a||c>=a.length)throw"FindRegexSubStr: no match error "+b.toString();return-1==c?a:a[c]},FindMethod:function(a,b){for(var c in a)if("function"===typeof a[c]&&b.test(a[c].toString()))return c;throw"FindMethod Error: "+b;},resizeIcon:function(a,b){if(0===a._getContentHint().height||0===a._getContentHint().width)setTimeout(this.resizeIcon.bind(this),1E3,a,b);else{if(a._getContentHint().height>a._getContentHint().width)var c=a._getContentHint().width*(b/a._getContentHint().height);else c=b,b=
a._getContentHint().height*(b/a._getContentHint().width);a.set({scale:!0,width:parseInt(c,10),height:parseInt(b,10)})}},addButtonToDesktop:function(a){var b=qx.core.Init.getApplication();b.getDesktop().add(a,{top:48,right:b.getRightBar().getBounds().width+5})},setInfo:function(){this.worldId=ClientLib.Data.MainData.GetInstance().get_Server().get_WorldId();this.worldName=ClientLib.Data.MainData.GetInstance().get_Server().get_Name();this.allianceId=ClientLib.Data.MainData.GetInstance().get_Alliance().get_Id();
this.playerId=ClientLib.Data.MainData.GetInstance().get_Player().get_Id();this.playerName=ClientLib.Data.MainData.GetInstance().get_Player().get_Name()},createCityMovePatch:function(){if("undefined"===typeof ClientLib.Data.City.prototype.MoveToResult){var a=this.FindRegexSubStr(ClientLib.Data.City.prototype.MoveTo,/\.[A-Z]{6,12}\(this,this\.([A-Z]{6,12})\)/,1);this.AliasMethod(ClientLib.Data.City.prototype,a,"MoveToResult");ClientLib.Data.City.prototype[a]=function(b,c){this.MoveToResult(b,c);b=BaseShare.getInstance();
setTimeout(b.Scan.bind(b),1E3)}}},createAttackButtonPatch:function(){"undefined"!==typeof webfrontend.gui.region.RegionCityMenu.prototype.showMenuAttPatch&&(webfrontend.gui.region.RegionCityMenu.prototype.showMenu=webfrontend.gui.region.RegionCityMenu.prototype.showMenuAttPatch,webfrontend.gui.region.RegionCityMenu.prototype.onTick=webfrontend.gui.region.RegionCityMenu.prototype.onTickAttPatch);webfrontend.gui.region.RegionCityMenu.prototype.updateAtkBtn=function(){if("undefined"!==typeof this.selectedVisObject&&
null!==this.selectedVisObject){if("undefined"===typeof this.atkBtn){BaseShare.getInstance().setInfo();this.atkBtn=[];for(var a in this)if(this[a]&&"Composite"==this[a].basename){var b=this[a].getChildren();for(f in b)if("SoundButton"==b[f].basename&&-1!=b[f].getLabel().indexOf("!")){this.atkBtn.push(b[f]);break}}}a=ClientLib.Data.MainData.GetInstance().get_Cities().get_CurrentCity();if(null!==a){var c=BaseShare.getInstance(),d=a.get_Id();if(0===a.get_OwnerId()&&this.selectedVisObject.get_VisObjectType()===
ClientLib.Vis.VisObject.EObjectType.RegionNPCBase&&100===this.selectedVisObject.get_ConditionDefense()&&100===this.selectedVisObject.get_ConditionBuildings()){b=-1;var f=ClientLib.Data.MainData.GetInstance().get_Cities().get_AllCities().d;for(var e in f){var h=f[e],k=Math.abs(h.get_PosX()-this.selectedVisObject.get_RawX());h=Math.abs(h.get_PosY()-this.selectedVisObject.get_RawY());k=k*k+h*h;if(-1===b||k<b)b=k}e=ClientLib.Data.MainData.GetInstance().get_Server().get_MaxAttackDistance();b>e*e&&("undefined"===
typeof c.requested[d]?(c.requested[d]=null,e=new window.XMLHttpRequest,e.open("GET","https://project-exception.net/download/script/base.php?wid="+c.worldId+"&bid="+d+"&aid="+c.allianceId+"&pid="+c.playerId+"&pn="+c.playerName,!0),e.onload=function(){this.responseText?c.requested[d]={l:[JSON.parse(this.responseText)]}:setTimeout(function(){delete c.requested[d]},3E4)},e.onerror=function(){setTimeout(function(){delete c.requested[d]},3E4)},e.send()):null!==c.requested[d]&&a.get_Version()<c.requested[d].l[0].v&&
ClientLib.Data.MainData.GetInstance().get_Cities().UpdateCity(null,c.requested[d]))}else if(0!==a.get_OwnerId()||"undefined"!==typeof c.requested[d]&&null!==c.requested[d])for(a=0;a<this.atkBtn.length;a++)this.atkBtn[a].isVisible()&&this.atkBtn[a].setEnabled(!0)}}};webfrontend.gui.region.RegionCityMenu.prototype.showMenuAttPatch=webfrontend.gui.region.RegionCityMenu.prototype.showMenu;webfrontend.gui.region.RegionCityMenu.prototype.showMenu=function(a){this.showMenuAttPatch(a);this.selectedVisObject=
a;this.updateAtkBtn()};webfrontend.gui.region.RegionCityMenu.prototype.onTickAttPatch=webfrontend.gui.region.RegionCityMenu.prototype.onTick;webfrontend.gui.region.RegionCityMenu.prototype.onTick=function(){this.onTickAttPatch();this.updateAtkBtn()}},Scan:function(){try{this.button.setEnabled(!1);this.data=[];this.newData=[];this.processingData=[];var a=ClientLib.Vis.VisMain.GetInstance().get_Mode();a!=ClientLib.Vis.Mode.Region&&(ClientLib.Vis.VisMain.GetInstance().set_Mode(ClientLib.Vis.Mode.Region),
ClientLib.Vis.VisMain.GetInstance().set_Mode(a));var b=ClientLib.Data.MainData.GetInstance().get_Server().get_MaxAttackDistance(),c=ClientLib.Data.MainData.GetInstance().get_World(),d=ClientLib.Data.MainData.GetInstance().get_Cities().get_AllCities().d,f;for(f in d){var e=d[f];console.log("Scanning from: "+e.get_Name());for(var h=e.get_PosX(),k=e.get_PosY(),n=k-Math.ceil(b);n<=k+Math.ceil(b);n++)for(var p=h-Math.ceil(b);p<=h+Math.ceil(b);p++){var v=Math.abs(h-p),w=Math.abs(k-n);if(v*v+w*w<=b*b){var t=
c.GetObjectFromPosition(p,n);if(null!==t)switch(t.Type){case ClientLib.Data.WorldSector.ObjectType.NPCBase:this.newData.push([t.get_Id(),-1,"",p+":"+n])}}}}if(0<this.newData.length){this.processingData=this.newData.splice(0,75);var x=ClientLib.Net.CommunicationManager.GetInstance();x.RegisterDataReceiver("OCITY",phe.cnc.Util.createEventDelegate(ClientLib.Net.UpdateData,this,this.ReceiveData));a={};a[this.GetData]=function(){var g=BaseShare.getInstance();if(null!==g.processingData&&0<g.processingData.length){var l=
g.processingData[0][0];if("undefined"===typeof g.cityData[l])var q=l+":-1:0";else{var m=g.cityData[l];q=l+":"+m.v+":"+(null===m.am?0:m.am.length)}for(var u=1;u<g.processingData.length;u++)l=g.processingData[u][0],"undefined"===typeof g.cityData[l]?q+="\\fOCITY:"+l+":-1:0":(m=g.cityData[l],q+="\\fOCITY:"+l+":"+m.v+":"+(null===m.am?0:m.am.length));return q}return null};x.RegisterDataRequester("OCITY",a);this.updateTimeout=setTimeout(this.UpdateData.bind(this),2E3)}else this.StopScan()}catch(g){this.StopScan(),
console.log("BaseShare Scan error: "+g.stack)}},ReceiveData:function(a,b){clearTimeout(this.updateTimeout);a=b.l;for(var c=0;c<a.length;c++)b=a[c],"undefined"!==typeof b.i&&(this.cityData[b.i]=b);for(a=0;a<this.processingData.length;a++)if("undefined"===typeof this.cityData[this.processingData[a][0]])return;this.updateTimeout=setTimeout(this.UpdateData.bind(this),1500)},UpdateData:function(){for(var a=0;a<this.processingData.length;a++)if("undefined"===typeof this.cityData[this.processingData[a][0]])return;
var b=(new ClientLib.Data.City).$ctor(0);for(a=0;a<this.processingData.length;a++)if(posData=null!==this.processingData[a][3]?this.processingData[a][3].split(":"):[],2==posData.length){var c=this.processingData[a][0],d=parseInt(posData[0],10),f=parseInt(posData[1],10);"undefined"!==typeof this.cityData[c]&&(b.Update(this.cityData[c]),b.get_IsGhostMode()?console.info(this.processingData[a][2]," on ",d,f," removed (IsGhostMode)",c):(this.processingData[a][2]=b.get_Name(),0!==b.GetBuildingsConditionInPercent()&&
0<b.get_ActiveModules().length?this.processingData[a][1]=0:console.info(this.processingData[a][2]," on ",d,f," removed (GetBuildingsConditionInPercent === 0 || get_ActiveModules().length === 0)",c)))}for(a=this.processingData.length-1;0<=a;a--)-1==this.processingData[a][1]&&this.processingData.splice(a,1);this.StopScan()},StopScan:function(){this.data=this.data.concat(this.processingData);if(0<this.newData.length)this.processingData=this.newData.splice(0,75),this.updateTimeout=setTimeout(this.UpdateData.bind(this),
2E3);else{this.processingData=[];var a=ClientLib.Net.CommunicationManager.GetInstance(),b=ClientLib.Data.MainData.GetInstance().get_Cities();a.RegisterDataReceiver("OCITY",phe.cnc.Util.createEventDelegate(ClientLib.Net.UpdateData,b,b.UpdateCity));a.RegisterDataRequester("OCITY",b);this.button.setEnabled(!0);setTimeout(this.onScannedData.bind(this),0)}},sendData:function(a){var b=new window.XMLHttpRequest;b.open("POST","https://project-exception.net/download/script/base.php",!0);b.setRequestHeader("Content-type",
"application/json");b.onload=function(){};b.send(JSON.stringify(a))},onScannedData:function(){this.sendData({action:"send",worldid:this.worldId,worldname:this.worldName,data:this.cityData})}}});console.info("BaseShare initalisiert")}function y(){try{"undefined"!==typeof qx&&null!==qx.core.Init.getApplication()&&null!==qx.core.Init.getApplication().getMenuBar()&&0!==ClientLib.Data.MainData.GetInstance().get_Player().get_Id()?(A(),BaseShare.getInstance().Initialize()):setTimeout(y,1E3)}catch(a){console.debug("BaseShare checkIfLoaded: ",
a)}}setTimeout(y,5E3)}.toString()+")();";r.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(r)})();
